export { AuthoraClient } from './client.js';
export { AuthoraAgent } from './agent.js';
export { generateKeyPair, getPublicKey, sign, verify, buildSignaturePayload, toBase64Url, fromBase64Url, sha256Hash } from './crypto.js';
export type { KeyPair } from './crypto.js';
export { matchPermission, matchAnyPermission } from './permissions.js';
export { AuthoraMCPGuard, AuthoraMCPMiddleware, protectTool } from './mcp.js';

export {
  AuthoraError,
  AuthenticationError,
  AuthorizationError,
  NetworkError,
  NotFoundError,
  RateLimitError,
  TimeoutError,
} from './errors.js';

export { AgentsResource } from './resources/agents.js';
export { RolesResource } from './resources/roles.js';
export { PermissionsResource } from './resources/permissions.js';
export { DelegationsResource } from './resources/delegations.js';
export { PoliciesResource } from './resources/policies.js';
export { McpResource } from './resources/mcp.js';
export { AuditResource, type AuditStreamOptions } from './resources/audit.js';
export { NotificationsResource } from './resources/notifications.js';
export { WebhooksResource } from './resources/webhooks.js';
export { AlertsResource } from './resources/alerts.js';
export { ApiKeysResource } from './resources/api-keys.js';
export { OrganizationsResource } from './resources/organizations.js';
export { WorkspacesResource } from './resources/workspaces.js';
export { ApprovalsResource } from './resources/approvals.js';
export { CreditsResource } from './resources/credits.js';
export { UserDelegationsResource } from './resources/user-delegations.js';

export type {
  AuthoraClientOptions,
  PaginatedList,
  PaginationParams,
  Agent,
  AgentStatus,
  CreateAgentParams,
  UpdateAgentParams,
  ListAgentsParams,
  ActivateAgentParams,
  RotateKeyParams,
  AgentVerification,
  Role,
  CreateRoleParams,
  ListRolesParams,
  UpdateRoleParams,
  AgentRoleAssignment,
  AssignRoleParams,
  PermissionCheckParams,
  PermissionCheckResult,
  BatchCheckItem,
  BatchPermissionCheckParams,
  BatchPermissionCheckResult,
  EffectivePermissions,
  Delegation,
  DelegationStatus,
  DelegationConstraints,
  CreateDelegationParams,
  ListDelegationsParams,
  BulkRevokeResult,
  DelegationVerification,
  VerifyDelegationParams,
  ListAgentDelegationsParams,
  Policy,
  PolicyEffect,
  PolicyPrincipals,
  CreatePolicyParams,
  ListPoliciesParams,
  UpdatePolicyParams,
  SimulatePolicyParams,
  EvaluatePolicyParams,
  PolicyVersion,
  PolicySimulationResult,
  PolicyEvaluationResult,
  McpServer,
  McpTransport,
  RegisterMcpServerParams,
  ListMcpServersParams,
  UpdateMcpServerParams,
  McpTool,
  RegisterMcpToolParams,
  McpProxyRequest,
  McpProxyResponse,
  AuditEvent,
  ListAuditEventsParams,
  GenerateReportParams,
  AuditReport,
  AuditMetricsParams,
  AuditMetrics,
  Notification,
  ListNotificationsParams,
  UnreadCountParams,
  UnreadCountResult,
  MarkAllReadParams,
  Webhook,
  CreateWebhookParams,
  ListWebhooksParams,
  UpdateWebhookParams,
  Alert,
  CreateAlertParams,
  ListAlertsParams,
  UpdateAlertParams,
  ApiKey,
  RotatedApiKey,
  CreateApiKeyParams,
  ListApiKeysParams,
  Organization,
  CreateOrganizationParams,
  ListOrganizationsParams,
  Workspace,
  WorkspaceStats,
  CreateWorkspaceParams,
  ListWorkspacesParams,
  AgentOptions,
  KeyRotationResult,
  SignedRequestOptions,
  SignedResponse,
  AgentDelegateParams,
  McpToolCallParams,
  CreateAgentResult,
  McpAuthoraMetadata,
  McpGuardOptions,
  McpMiddlewareOptions,
  McpToolContext,
  ApprovalStatus,
  RiskLevel,
  ApprovalChallenge,
  ListApprovalsParams,
  ApprovalStats,
  DecideApprovalParams,
  BulkDecideParams,
  BulkDecideResult,
  PermissionSuggestion,
  ApprovalSettings,
  UpdateApprovalSettingsParams,
  TestAiParams,
  TestAiResult,
  ApprovalPattern,
  ListPatternsParams,
  EscalationStep,
  EscalationRule,
  CreateEscalationRuleParams,
  UpdateEscalationRuleParams,
  PushSubscribeParams,
  ApprovalWebhook,
  CreateApprovalWebhookParams,
  UpdateApprovalWebhookParams,
  CreditBalance,
  CreditTransaction,
  ListCreditTransactionsParams,
  CreditCheckoutParams,
  CreditCheckoutResult,
  WebhookEventType,
  UserDelegationGrant,
  UserDelegationGrantStatus,
  ConsentMethod,
  CreateUserDelegationParams,
  ListUserDelegationParams,
  UserDelegationToken,
  IssueUserDelegationTokenParams,
  RefreshUserDelegationTokenParams,
  VerifyUserDelegationTokenResult,
  DelegationRequestParams,
  UserDelegationContext,
  McpDelegationContext,
  AgentDelegationJwt,
  IssueAgentDelegationJwtParams,
  VerifyAgentDelegationJwtResult,
} from './types.js';
